[package]
name = "subprocess"
version = "0.1.12"
authors = ["Hrvoje Nikšić <hniksic@gmail.com>"]
readme = "README.md"
keywords = ["execute", "process", "command", "redirect", "pipe"]
license = "Apache-2.0/MIT"
repository = "https://github.com/hniksic/rust-subprocess"
documentation = "https://docs.rs/subprocess/"
description = """
Execution of child processes and pipelines, inspired by Python's subprocess
module, with Rust-specific extensions.
"""

[dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
crossbeam = "0.2.10"
kernel32-sys = "0.2.2"
winapi = "0.2.8"

[dev-dependencies]
tempdir = "0.3.5"

[lib]
name = "subprocess"
path = "src/lib.rs"
