[package]
name = "subprocess"
version = "0.1.0"
authors = ["Hrvoje Niksic <hniksic@gmail.com>"]
description = "Execution and interaction with external processes"
license = "Apache-2.0/MIT"
repository = "https://github.com/hniksic/rust-subprocess"
#documentation = "..."

[dependencies]
libc = "0.2"
crossbeam = "0.2.10"
kernel32-sys = "0.2.2"
winapi = "0.2.8"

[dev-dependencies]
tempdir = "0.3.5"

[lib]
name = "subprocess"
path = "src/lib.rs"

[[bin]]
name = "sample"

[[bin]]
name = "just-echo"
