[package]
name = "subprocess"
version = "0.1.6"
authors = ["Hrvoje Niksic <hniksic@gmail.com>"]
description = "Execution of child processes and pipelines, inspired by Python's subprocess module with Rust-specific extensions."
readme = "README.md"
keywords = ["execute", "process", "command", "redirect", "pipe"]
categories = ["os"]
license = "Apache-2.0/MIT"
repository = "https://github.com/hniksic/rust-subprocess"
documentation = "https://docs.rs/subprocess/"

[dependencies]
libc = "0.2"
crossbeam = "0.2.10"
kernel32-sys = "0.2.2"
winapi = "0.2.8"

[dev-dependencies]
tempdir = "0.3.5"

[lib]
name = "subprocess"
path = "src/lib.rs"

[[bin]]
name = "sample"

[[bin]]
name = "just-echo"
